# -*- coding: utf-8 -*-
"""s3_bucket_upload.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W15rcSlBs5AuqGXYHAegwadr-s209jmk
"""

import boto3
import os

access_key = "AKIAJL2IQX7Z5KVSM5ZQ"
secret_access_key = "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"

client = boto3.client('s3',access_key=access_key,secret_access_key=secret_access_key)
for file in os.dir():
  if '.py' in file:
    bucket_name = ""
    path="python/"+str(file)
    client.upload_file(file,bucket_name,path)

